version: '3.8'

services:
  # Base de données PostgreSQL
  db:
    build: ./db
    env_file: .env
    networks:
      internal:
        ipv4_address: 172.20.0.10
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Serveur DNS (Bind9)
  dns:
    image: ubuntu/bind9:latest
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    volumes:
      - ./dns/config:/etc/bind
      - ./dns/zones:/var/lib/bind
    networks:
      internal:
        ipv4_address: 172.20.0.40
    command: /usr/sbin/named -4 -f -u bind
    restart: unless-stopped

  # Application Web (Django + Nginx)
  web:
    build: ./web
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi
    volumes:
      - ./web:/app
    networks:
      internal:
        ipv4_address: 172.20.0.20
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./web/staticfiles:/app/staticfiles
    depends_on:
      - web
    networks:
      internal:
        ipv4_address: 172.20.0.50


  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Interface web
    networks:
      internal:
        ipv4_address: 172.20.0.30
    restart: unless-stopped
    
    #Production
  # mail:
  #   build: ./mail
  #   hostname: mail.startup.tg
  #   networks:
  #     internal:
  #       ipv4_address: 172.20.0.30
  #   ports:
  #     - "25:25"    # SMTP
  #     - "587:587"  # Submission
  #     - "465:465"  # SMTPS
  #   volumes:
  #     - mail_logs:/var/log/mail
  #     - mail_data:/var/mail
  #     # - sasl_data:/etc/sasldb2
  #   cap_add:
  #     - SYS_ADMIN 
  #   environment:
  #     - POSTFIX_MYNETWORKS=172.20.0.0/24 127.0.0.0/8
  #     - POSTFIX_MYDOMAIN=startup.tg
  #   restart: unless-stopped 


  # Firewall (Personnalisé)
  firewall:
    build:
      context: ./firewall
      dockerfile: Dockerfile
    networks:
      - internal
      - external
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  internal:
    ipam:
      config:
        - subnet: "172.20.0.0/24"
  external:

volumes:
  db_data:
  static_volume:
  media_volume:
  mailhog_data:
  # mail_logs:
  # mail_data:
  # sasl_data: