upstream django {
    server 172.20.0.20:8000;  # Utilisez l'IP explicite
}

server {
    listen 80;
    server_name webapp1.startup.tg localhost;
    
    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Ajoutez ces headers pour éviter les erreurs CORS
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_redirect off;
    }
    
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}