Domain                  startup.tg
KeyFile                 /etc/opendkim/keys/mail.private
Selector                mail
Socket                  inet:8891@127.0.0.1
PidFile                 /run/opendkim/opendkim.pid
UserID                  opendkim:opendkim
Mode                    sv
Syslog                  yes
